unified arguments of CreateRandomSubsetOfSize: having T[] with long and IEnumerable<T> with int caused "error CS0121: The call is ambiguous ..." when used with T[] and int